version: '3'

services:
  server:
    build: ./
    image: graphql-server
    depends_on:
      - prisma
    ports:
      - "4000:4000"
  prisma:
    image: prismagraphql/prisma:1.13
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma-password
            migrations: true
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma-password
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: